export {staffGetNotification} from "./staffNotification";
export {staffgetProfile} from "./staffGetProfile";
export {staffGetStudentProjects} from "./staffGetStudentProjects";
export {staffGetTeamProjects} from "./staffGetTeamProjects";
export {doctorRequestToBeSuberVisorProject} from "./doctorRequestToBeSuberVisorProject";
export {TARequestToBeSuberVisor} from "./TARequestToBeSuberVisor";
export {staffGetItsTeams} from "./staffGetItsTeams";
export {staffGetDoctorProjects} from "./staffDoctorProjects";
export {staffAddDoctorProject} from "./staffDoctorProjects"