export * from "./admin";
export { default as loginRequests } from "./loginRequests";
export { default as adminLoginRequest } from "./adminLoginRequest";
export { default as getAllDepartments } from "./getAllDepartments";
export { default as getTeamProjects } from "./getTeamProjects";
export { default as getAllTechnologies } from "./getAllTechnologies";
export { default as addTeamProjectRequests } from "./addTeamProjectRequests";
export { default as editTeamProjectRequests } from "./editTeamProjectRequests";
export { default as deleteTeamProjectRequests } from "./deleteTeamProjectRequests";
export { default as getOldProjects } from "./getOldProjects";
export { default as getAllStudents } from "./getAllStudents";
export { default as getOneStudent } from "./getOneStudent";
export { default as getAllDoctors } from "./getAllDoctors";
export { default as getAllTAs } from "./getAllTAs";
