export { default as adminOldProjectsRequest} from "./adminOldProjectsRequest";
export { adminAddOldProjects } from "./adminOldProjectsRequest";
export { adminEditOldProjects } from "./adminOldProjectsRequest";
export { adminDeleteOldProjects} from "./adminOldProjectsRequest";
export { adminGetFeeds } from "./adminFeeds";
export { adminAddFeed } from "./adminFeeds";
export { adminDeleteDepartment } from "./adminDepartments";
export { adminAddDepartment } from "./adminDepartments";
export { adminEditDepartment } from "./adminDepartments";
export { adminGetCurrentProjects } from "./adminCurrentProject";
export { adminGetDoctors } from "./adminDrs";
export { adminAddDoctor } from "./adminDrs";
export { adminGetTas } from "./adminTas";
export { adminDeleteStaff } from "./adminDrs";
export { adminAddTa } from "./adminTas";
export { adminGetStudents } from "./adminStudent";
export { adminAddStudent } from "./adminStudent";