export { default as AdminLoginPage } from "./AdminLoginPage";
export { default as AdminDashboard } from "./AdminDashboard";
export { default as AdminStat } from "./AdminStat";
export { default as TeamTablePage } from "./TeamTablePage";
export { default as TATablePage } from "./TATablePage";
export { default as DoctorsTablePage } from "./DoctorsTablePage";
export { default as StudentsTablePage } from "./StudentsTablePage";
export { default as AdminRules } from "./AdminRules";
export {default as AdminNewsfeed} from "./AdminNewsFeed";
export { default as AdminOldProjects} from "./AdminOldProjects";
export {default as AdminProjects} from "./AdminProjects";
export {default as AdminTechnologies } from "./AdminTechnologies";