export { default as EditProject } from "./EditProject";
export { default as SupervisedProjectSeeMore } from "./SupervisedProjectSeeMore";
export { default as AddDatatableRow } from "./AddDatatableRow";
export { default as AskToJoinMyTeam } from "./AskToJoinMyTeam";
export {default as AddNewsFeed} from "./AddNewsFeed";
export { default as AddOldProjectRow} from "./AddOldProjectRow";
export { default as EditOldProjectRow} from "./EditOldProjectDataTableRow";
export { default as AddDepartmentRow } from "./AddDepartmentRow";
export { default as EditDepartmentRow } from "./EditDepartmentRow";
export { default as AddDoctorProject } from "./AddDoctorProject";